# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '3.7' 

services: 
  salt-master:
    hostname: salt-master 
    build:
      dockerfile: ./salt-master/Dockerfile

  salt-minion:
    build:
      dockerfile: ./salt-minion/Dockerfile
    depends_on:
      - salt-master
